name: Upload release assets
on:
  release:
    types: [published]
jobs:
  upload_assets:
    name: Build and upload assets for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        name: [
            linux,
            windows,
            macos
        ]
        include:
          - name: linux
            os: ubuntu-latest
            artifact_name: target/release/restorable
            asset_name: restorable-linux
          - name: windows
            os: windows-latest
            artifact_name: target/release/restorable.exe
            asset_name: restorable-windows
          - name: macos
            os: macos-latest
            artifact_name: target/release/restorable
            asset_name: restorable-macos

    steps:
    - uses: actions/checkout@v1

    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - name: Build
      run: cargo build --release --locked

    - name: Upload binaries to release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_name: ${{ matrix.asset_name }}
        asset_path: ${{ matrix.artifact_name }}
        asset_content_type: application/octet-stream
